name: XiuXianCore
version: '3.4.0'
main: com.xiuxian.XiuXian
api-version: '1.21'
softdepend:
  - BentoBox
  - PlaceholderAPI
commands:
  xw:
    description: 'xiuxian command'
    usage: /xw [lianti|xiufa|leixing|addxp|setlevel|addlevel]
permissions:
  xiuxian.admin:
    description: 'admin permission'
    default: op
